server:
  port: 8761

spring:
  application:
    name: SERVICE-REGISTRY

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

